ARG BUILDER=golang:alpine3.15
ARG MAINNET_RUNNER=quay.io/team-helium/blockchain-node:blockchain-node-1.1.56
ARG TESTNET_RUNNER=quay.io/team-helium/blockchain-node:blockchain-node-testnet-1.1.56
ARG NETWORK=mainnet


FROM $BUILDER as rosetta-builder

WORKDIR /src

ENV PATH="/src/go/bin:$PATH" \
    CGO_ENABLED=0

COPY . rosetta-helium

RUN cd rosetta-helium && go build -o rosetta-helium


FROM ${MAINNET_RUNNER} as runner-mainnet

WORKDIR /app

COPY --from=rosetta-builder /src/rosetta-helium/rosetta-helium rosetta-helium
COPY --from=rosetta-builder /src/rosetta-helium/docker/mainnet.sh start.sh
COPY --from=rosetta-builder /src/rosetta-helium/helium-constructor helium-constructor


FROM ${TESTNET_RUNNER} as runner-testnet

WORKDIR /app

COPY --from=rosetta-builder /src/rosetta-helium/rosetta-helium rosetta-helium
COPY --from=rosetta-builder /src/rosetta-helium/docker/testnet.sh start.sh
COPY --from=rosetta-builder /src/rosetta-helium/helium-constructor helium-constructor


FROM runner-${NETWORK} as rosetta-helium-final

EXPOSE 8080
EXPOSE 44158

RUN apk add --no-cache --update \
    ca-certificates git npm

RUN cd helium-constructor \
      && npm install \
      && npm run build \
      && chmod +x /app/start.sh

ENTRYPOINT ["/app/start.sh"]